
[[main]]
    parent = "Procedures"
    name = "Diagnostic Procedures"
    url = "/procedures/#diagnostic-procedures"
    weight = 11
[[main]]
    parent = "Diagnostic Procedures"
    name = "Flexible Bronchoscopy"
    url = "/procedures/#flexible-bronchoscopy"
    weight = 12
[[main]]
    parent = "Diagnostic Procedures"
    name = "Endobronchial Ultrasound (EBUS)"
    url = "/procedures/#endobronchial-ultrasound"
    weight = 13
[[main]]
    parent = "Diagnostic Procedures"
    name = "Radial EBUS"
    url = "/procedures/#radial-ebus"
    weight = 14
[[main]]
    parent = "Diagnostic Procedures"
    name = "Transbronchial Needle Aspiration (TBNA)"
    url = "/procedures/#transbronchial-needle-aspiration"
    weight = 15
[[main]]
    parent = "Diagnostic Procedures"
    name = "Robotic-Assisted Bronchoscopy"
    url = "/procedures/#robotic-assisted-bronchoscopy"
    weight = 16
[[main]]
    parent = "Procedures"
    name = "Therapeutic Procedures"
    url = "/procedures/#therapeutic-procedures"
    weight = 20
[[main]]
    parent = "Therapeutic Procedures"
    name = "Bronchial Thermoplasty"
    url = "/procedures/#bronchial-thermoplasty"
    weight = 21
[[main]]
    parent = "Therapeutic Procedures"
    name = "Airway Stenting"
    url = "/procedures/#airway-stenting"
    weight = 22
[[main]]
    parent = "Therapeutic Procedures"
    name = "Balloon Dilation"
    url = "/procedures/#balloon-dilation"
    weight = 23
[[main]]
    parent = "Therapeutic Procedures"
    name = "Cryotherapy"
    url = "/procedures/#cryotherapy"
    weight = 24
[[main]]
    parent = "Therapeutic Procedures"
    name = "Electrocautery and Argon Plasma Coagulation (APC)"
    url = "/procedures/#electrocautery-and-argon-plasma-coagulation"
    weight = 25
[[main]]
    parent = "Therapeutic Procedures"
    name = "Microdebrider Bronchoscopy"
    url = "/procedures/#microdebrider-bronchoscopy"
    weight = 26
[[main]]
    parent = "Therapeutic Procedures"
    name = "Pulsed Electrical Field Therapy"
    url = "/procedures/#pulsed-electrical-field-therapy"
    weight = 27
[[main]]
    parent = "Procedures"
    name = "Pleural Procedures"
    url = "/procedures/#pleural-procedures"
    weight = 30
[[main]]
    parent = "Pleural Procedures"
    name = "Thoracentesis"
    url = "/procedures/#thoracentesis"
    weight = 31
[[main]]
    parent = "Pleural Procedures"
    name = "Pleurodesis"
    url = "/procedures/#pleurodesis"
    weight = 32
[[main]]
    parent = "Pleural Procedures"
    name = "Indwelling Pleural Catheter (IPC) Placement"
    url = "/procedures/#indwelling-pleural-catheter-placement"
    weight = 33
[[main]]
    parent = "Pleural Procedures"
    name = "Medical Thoracoscopy/Pleuroscopy"
    url = "/procedures/#medical-thoracoscopy-pleuroscopy"
    weight = 34
[[main]]
    parent = "Pleural Procedures"
    name = "Pleural Biopsy"
    url = "/procedures/#pleural-biopsy"
    weight = 35
[[main]]
    parent = "Procedures"
    name = "Miscellaneous Procedures"
    url = "/procedures/#miscellaneous-procedures"
    weight = 40
[[main]]
    parent = "Miscellaneous Procedures"
    name = "Bronchoscopic Lung Volume Reduction (BLVR)"
    url = "/procedures/#bronchoscopic-lung-volume-reduction"
    weight = 41
[[main]]
    parent = "Miscellaneous Procedures"
    name = "Endoscopic Valve Placement"
    url = "/procedures/#endoscopic-valve-placement"
    weight = 42
[[main]]
    parent = "Miscellaneous Procedures"
    name = "Percutaneous Tracheostomy"
    url = "/procedures/#percutaneous-tracheostomy"
    weight = 43